version: "3.8"

services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ud_php_fpm
    expose:
        - "9000"
    volumes:
      - ./:/var/www/html
    networks:
      - laravel

  nginx:
    image: nginx:stable-alpine
    container_name: ud_nginx
    expose:
        - "8080"
    ports:
      - "8088:8080"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: ud_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpass
    ports:
      - "3309:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
